---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fiberplane-proxy
data:
  data_sources.yaml: |
    - name: prometheus
      description: Prometheus
      providerType: prometheus
      config:
        url: http://prom-server
